# Quantitative Momentum Strategy

"Momentum investing" means investing in the stocks that have increased in price the most.

For this project, we're going to build an investing strategy that selects the 50 stocks with the highest price momentum. From there, we will calculate recommended trades for an equal-weight portfolio of these 50 stocks.


## Library Imports

The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [2]:
import numpy as np
import pandas as pd
# import requests
import math
from scipy import stats
import xlsxwriter
from datetime import datetime
import yfinance as yf
from statistics import mean

## Importing Our List of Stocks

As before, we'll need to import our list of stocks and our API token before proceeding. Make sure the `.csv` file is still in your working directory and import it with the following command:

In [2]:
stocks = pd.read_csv('/Users/lin/github/quant/sp_500_stocks.csv')

In [3]:
stocks.head(100)

   Ticker
0       A
1     AAL
2     AAP
3    AAPL
4    ABBV
..    ...
95   CINF
96     CL
97    CLX
98    CMA
99  CMCSA

[100 rows x 1 columns]

## Making Our First API Call

It's now time to make the first version of our momentum screener!

We need to get one-year price returns for each stock in the universe. Here's how.

In [57]:
symbol = 'CINF'
tickerData = yf.Ticker(symbol)

In [58]:
# Get the historical prices for this ticker
# ticker_df_p1 = tickerData.history(start='2024-07-15', end='2024-07-19')
# ticker_df_p2 = tickerData.history(start='2025-07-15', end='2025-07-19')

In [59]:
ticker_df = tickerData.history(period='1y', end='2025-08-08')

#### Validate `fiftyTwoWeekChangePercent`

In [60]:
ticker_df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-08-08 00:00:00-04:00,123.657626,124.712443,123.599027,124.390137,367400,0.0,0.0
2024-08-09 00:00:00-04:00,124.263165,125.278915,123.501347,125.191002,296700,0.0,0.0
2024-08-12 00:00:00-04:00,125.054279,125.542620,123.843204,123.901802,275400,0.0,0.0
2024-08-13 00:00:00-04:00,124.790569,125.601224,123.696691,125.474251,412000,0.0,0.0
2024-08-14 00:00:00-04:00,125.396124,127.622957,124.683151,127.036957,553900,0.0,0.0
...,...,...,...,...,...,...,...
2025-08-01 00:00:00-04:00,146.789993,146.789993,143.869995,146.190002,694700,0.0,0.0
2025-08-04 00:00:00-04:00,146.520004,149.779999,146.520004,149.740005,523300,0.0,0.0
2025-08-05 00:00:00-04:00,150.389999,151.139999,149.500000,150.429993,569200,0.0,0.0
2025-08-06 00:00:00-04:00,150.850006,154.429993,150.429993,154.050003,811800,0.0,0.0
2025-08-07 00:00:00-04:00,154.449997,154.449997,150.789993,151.470001,534700,0.0,0.0

In [61]:
last_price = ticker_df['Close'].iloc[-1]
first_price = ticker_df['Open'].iloc[0]

In [62]:
last_price

np.float64(151.47000122070312)

In [63]:
first_price

np.float64(123.65762570986202)

In [64]:
price_change = last_price / first_price - 1

In [65]:
price_change

np.float64(1.2249143581011115)

In [66]:
tickerData.info['fiftyTwoWeekChangePercent']

18.169762

## Parsing Our API Call

This API call has all the information we need. We can parse it using the same square-bracket notation as in the first project of this course. Here is an example.

## Executing A Batch API Call & Building Our DataFrame

Just like in our first project, it's now time to execute several batch API calls and add the information we need to our DataFrame.

We'll start by running the following code cell, which contains some code we already built last time that we can re-use for this project. More specifically, it contains a function called `chunks` that we can use to divide our list of securities into groups of 100.

In [6]:
# Function sourced from 
# https://stackoverflow.com/questions/312443/how-do-you-split-a-list-into-evenly-sized-chunks
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]   
        
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(' '.join(symbol_groups[i]))

Now we need to create a blank DataFrame and add our data to the data frame one-by-one.

In [5]:
%%time
final_dataframe = pd.DataFrame()

for symbol_string in symbol_strings:
    tickers = yf.Tickers(symbol_string) 
    for symbol in symbol_string.split(' '):
        try:
            return_1year = tickers.tickers[symbol].info['fiftyTwoWeekChangePercent']
            price = tickers.tickers[symbol].info['currentPrice']
        except:
            print(f"{symbol} is skipped")
            pass  
        series = pd.Series([symbol, price, return_1year, 'N/A'])
        final_dataframe = pd.concat([final_dataframe, series.to_frame().T], ignore_index=True)
        
final_dataframe.columns = ['Ticker', 'Price', 'One-Year Price Return', 'Number of Shares to Buy']

NameError: name 'symbol_strings' is not defined

In [73]:
final_dataframe.head(10)

  Ticker   Price One-Year Price Return Number of Shares to Buy
0      A   113.5            -15.738678                     N/A
1    AAL   11.03             18.857754                     N/A
2    AAP   52.71            -10.448522                     N/A
3   AAPL  202.38               -3.2924                     N/A
4   ABBV  195.22              5.890644                     N/A
5    ABC  195.22              5.890644                     N/A
6   ABMD  195.22              5.890644                     N/A
7    ABT  127.29              17.17757                     N/A
8    ACN  255.37            -18.604576                     N/A
9   ADBE   347.8            -31.712872                     N/A

## Removing Low-Momentum Stocks

The investment strategy that we're building seeks to identify the 50 highest-momentum stocks in the S&P 500.

Because of this, the next thing we need to do is remove all the stocks in our DataFrame that fall below this momentum threshold. We'll sort the DataFrame by the stocks' one-year price return, and drop all stocks outside the top 50.

In [76]:
final_dataframe.sort_values('One-Year Price Return', ascending=False, inplace=True)

In [77]:
final_dataframe.reset_index(inplace=True)

In [78]:
top50_df = final_dataframe[:50]

In [79]:
top50_df

    index Ticker    Price One-Year Price Return Number of Shares to Buy
0     441    TPR   106.31             188.41562                     N/A
1     340    NRG   167.63             143.32996                     N/A
2     391     RE   314.25             124.83366                     N/A
3     390    RCL   314.25             124.83366                     N/A
4     454    UAL    84.57             123.25766                     N/A
5     233    HWM   184.26            112.403465                     N/A
6      50   AVGO   288.64             103.15316                     N/A
7      84    CCL    29.07             101.87499                     N/A
8     332   NFLX   1158.6              93.56779                     N/A
9     354   ORCL   244.42               91.1622                     N/A
10    275     LB    55.39             84.571815                     N/A
11    397     RL   293.77             83.836044                     N/A
12     44    APH   104.31              78.64361                     N/A
13    479    WDC    76.55             77.707756                     N/A
14    195   FTNT    97.36               75.7718                     N/A
15    345   NVDA   173.72              72.94176                     N/A
16    198     GE   269.38              70.10609                     N/A
17    152   EBAY    91.74              67.83754                     N/A
18    422    STX   154.81              67.28982                     N/A
19    293    LYV   146.14              65.95503                     N/A
20    385    PWR   395.17              64.94281                     N/A
21    386    PXD   395.17              64.94281                     N/A
22    202    GLW    62.05              64.32733                     N/A
23    182   FFIV   307.43             64.278076                     N/A
24     75      C    91.83             63.369514                     N/A
25     64     BK    99.81             62.504066                     N/A
26    256    JCI   106.48              62.04535                     N/A
27    328   NCLH     24.5              59.81735                     N/A
28     65   BKNG  5386.29             59.196136                     N/A
29    172   EXPE   178.06             58.811985                     N/A
30     77    CAH    156.0              58.60106                     N/A
31    448   TWTR   220.58             58.133198                     N/A
32    447   TTWO   220.58             58.133198                     N/A
33    107    COG   207.47              57.86791                     N/A
34    106    COF   207.47              57.86791                     N/A
35     25    ALK    51.37              56.04496                     N/A
36    167    ETR    89.67              55.25929                     N/A
37    457   ULTA   507.73             55.136276                     N/A
38    201     GL   137.24              54.84599                     N/A
39    210     GS   709.57              54.58368                     N/A
40    426    SYF    67.53              54.28375                     N/A
41    343   NTRS   127.06              54.04947                     N/A
42    407   SCHW    95.53               53.3633                     N/A
43    396    RJF   163.03             53.238083                     N/A
44    192    FRC    55.54              52.75028                     N/A
45    191   FOXA    55.54              52.75028                     N/A
46    199   GILD   113.18             51.249504                     N/A
47    318     MS   139.09             51.069843                     N/A
48    115   CSCO    67.11                  50.0                     N/A
49    481   WELL   166.24              49.71181                     N/A

## Calculating the Number of Shares to Buy

Just like in the last project, we now need to calculate the number of shares we need to buy. The one change we're going to make is wrapping this functionality inside a function, since we'll be using it again later in this Jupyter Notebook.

Since we've already done most of the work on this, try to complete the following two code cells without watching me do it first!

In [40]:
def portfolio_input():
    global portfolio_size
    portfolio_size = input('Enter the size of your portfolio: ')

    try: 
        print(float(portfolio_size))
        
    except ValueError:
        print('This is not a number! \nplease try again')

In [86]:
portfolio_input()

Enter the size of your portfolio:  50000

50000.0

In [80]:
top50_df.shape[0]

50

In [87]:
position_size = float(portfolio_size)/top50_df.shape[0]

In [88]:
position_size

1000.0

In [93]:
for i in range(top50_df.shape[0]):
    top50_df.loc[i, 'Number of Shares to Buy'] = math.floor(position_size/top50_df.loc[i, 'Price'])

In [94]:
top50_df

    index Ticker    Price One-Year Price Return Number of Shares to Buy
0     441    TPR   106.31             188.41562                       9
1     340    NRG   167.63             143.32996                       5
2     391     RE   314.25             124.83366                       3
3     390    RCL   314.25             124.83366                       3
4     454    UAL    84.57             123.25766                      11
5     233    HWM   184.26            112.403465                       5
6      50   AVGO   288.64             103.15316                       3
7      84    CCL    29.07             101.87499                      34
8     332   NFLX   1158.6              93.56779                       0
9     354   ORCL   244.42               91.1622                       4
10    275     LB    55.39             84.571815                      18
11    397     RL   293.77             83.836044                       3
12     44    APH   104.31              78.64361                       9
13    479    WDC    76.55             77.707756                      13
14    195   FTNT    97.36               75.7718                      10
15    345   NVDA   173.72              72.94176                       5
16    198     GE   269.38              70.10609                       3
17    152   EBAY    91.74              67.83754                      10
18    422    STX   154.81              67.28982                       6
19    293    LYV   146.14              65.95503                       6
20    385    PWR   395.17              64.94281                       2
21    386    PXD   395.17              64.94281                       2
22    202    GLW    62.05              64.32733                      16
23    182   FFIV   307.43             64.278076                       3
24     75      C    91.83             63.369514                      10
25     64     BK    99.81             62.504066                      10
26    256    JCI   106.48              62.04535                       9
27    328   NCLH     24.5              59.81735                      40
28     65   BKNG  5386.29             59.196136                       0
29    172   EXPE   178.06             58.811985                       5
30     77    CAH    156.0              58.60106                       6
31    448   TWTR   220.58             58.133198                       4
32    447   TTWO   220.58             58.133198                       4
33    107    COG   207.47              57.86791                       4
34    106    COF   207.47              57.86791                       4
35     25    ALK    51.37              56.04496                      19
36    167    ETR    89.67              55.25929                      11
37    457   ULTA   507.73             55.136276                       1
38    201     GL   137.24              54.84599                       7
39    210     GS   709.57              54.58368                       1
40    426    SYF    67.53              54.28375                      14
41    343   NTRS   127.06              54.04947                       7
42    407   SCHW    95.53               53.3633                      10
43    396    RJF   163.03             53.238083                       6
44    192    FRC    55.54              52.75028                      18
45    191   FOXA    55.54              52.75028                      18
46    199   GILD   113.18             51.249504                       8
47    318     MS   139.09             51.069843                       7
48    115   CSCO    67.11                  50.0                      14
49    481   WELL   166.24              49.71181                       6

## Building a Better (and More Realistic) Momentum Strategy

Real-world quantitative investment firms differentiate between "high quality" and "low quality" momentum stocks:

* High-quality momentum stocks show "slow and steady" outperformance over long periods of time
* Low-quality momentum stocks might not show any momentum for a long time, and then surge upwards.

The reason why high-quality momentum stocks are preferred is because low-quality momentum can often be cause by short-term news that is unlikely to be repeated in the future (such as an FDA approval for a biotechnology company).

To identify high-quality momentum, we're going to build a strategy that selects stocks from the highest percentiles of: 

* 1-month price returns
* 3-month price returns
* 6-month price returns
* 1-year price returns

Let's start by building our DataFrame. You'll notice that I use the abbreviation `hqm` often. It stands for `high-quality momentum`.

In [22]:
hqm_columns = [
    'Ticker',
    'Price',
    'Number of Shares to Buy',
    'One-year Price Return',
    'One-year Return Percentile',
    'Six-month Price Return',
    'Six-month Return Percentile',
    'Three-month Price Return',
    'Three-month Return Percentile',
    'One-month Price Return',
    'One-month Return Percentile',
]

hqm_df = pd.DataFrame(columns=hqm_columns)

In [29]:
hqm_df

,0,1,2,3,4,5,6,7,8,9,10
0,A,124.96,N/A,0.886333,N/A,0.978855,N/A,1.070741,N/A,1.043507,N/A
1,AAL,13.25,N/A,1.293945,N/A,0.909403,N/A,1.138316,N/A,1.141258,N/A
2,AAP,60.52,N/A,1.32628,N/A,1.65543,N/A,1.149734,N/A,1.052339,N/A
3,AAPL,232.56,N/A,1.015395,N/A,0.983875,N/A,1.143648,N/A,1.087048,N/A
4,ABBV,207.92,N/A,1.098755,N/A,1.031854,N/A,1.143115,N/A,1.099233,N/A
...,...,...,...,...,...,...,...,...,...,...,...
500,YUM,145.47,N/A,1.08671,N/A,0.948197,N/A,1.015852,N/A,1.006643,N/A
501,ZBH,105.06,N/A,0.922649,N/A,1.007138,N/A,1.140332,N/A,1.098609,N/A
502,ZBRA,322.0,N/A,0.932145,N/A,1.038542,N/A,1.100667,N/A,0.954753,N/A
503,ZION,57.815,N/A,1.203456,N/A,1.092248,N/A,1.233231,N/A,1.048124,N/A
504,ZTS,154.79,N/A,0.851901,N/A,0.939367,N/A,0.936039,N/A,1.031796,N/A

In [24]:
symbol = 'CINF'
tickerData = yf.Ticker(symbol)
ticker_df = tickerData.history(period='1y', end='2025-08-15')
last_price = ticker_df['Close'].iloc[-1]
first_price = ticker_df['Open'].iloc[0]

In [31]:
price_change = float(last_price / first_price)

In [32]:
price_change

1.2069311370498426

In [27]:
hqm_columns = [
    'Ticker',
    'Price',
    'Number of Shares to Buy',
    'One-year Price Return',
    'One-year Return Percentile',
    'Six-month Price Return',
    'Six-month Return Percentile',
    'Three-month Price Return',
    'Three-month Return Percentile',
    'One-month Price Return',
    'One-month Return Percentile',
    
]

hqm_df = pd.DataFrame(columns=hqm_columns)
today = datetime.today().strftime('%Y-%m-%d')


for symbol_string in symbol_strings:
    tickers = yf.Tickers(symbol_string) 
    for symbol in symbol_string.split(' '):
        print(symbol)
        try:
            
            tickerData = yf.Ticker(symbol)
            ticker_df = tickerData.history(period='1y', end=today)
            last_price = ticker_df['Close'].iloc[-1]
            first_price = ticker_df['Open'].iloc[0]
            return_1y = float(last_price / first_price)

            ticker_df = tickerData.history(period='6mo', end=today)
            last_price = ticker_df['Close'].iloc[-1]
            first_price = ticker_df['Open'].iloc[0]
            return_6m = float(last_price / first_price)

            ticker_df = tickerData.history(period='3mo', end=today)
            last_price = ticker_df['Close'].iloc[-1]
            first_price = ticker_df['Open'].iloc[0]
            return_3m = float(last_price / first_price)

            ticker_df = tickerData.history(period='1mo', end=today)
            last_price = ticker_df['Close'].iloc[-1]
            first_price = ticker_df['Open'].iloc[0]
            return_1m = float(last_price / first_price)
            
            price = tickers.tickers[symbol].info['currentPrice']
        except:
            print(f"{symbol} is skipped")
            pass  
            
        series = pd.Series([symbol, price, 'N/A', return_1y, 'N/A', return_6m, 'N/A', return_3m, 'N/A', return_1m, 'N/A'])
        hqm_df = pd.concat([hqm_df, series.to_frame().T], ignore_index=True)

A
AAL
AAP
AAPL
ABBV
ABC

$ABC: possibly delisted; no timezone found

ABC is skipped
ABMD

$ABMD: possibly delisted; no timezone found

ABMD is skipped
ABT
ACN
ADBE
ADI
ADM
ADP
ADSK
AEE
AEP
AES
AFL
AIG
AIV
AIZ
AJG
AKAM
ALB
ALGN
ALK
ALL
ALLE
ALXN

$ALXN: possibly delisted; no timezone found

ALXN is skipped
AMAT
AMCR
AMD
AME
AMGN
AMP
AMT
AMZN
ANET
ANSS

$ANSS: possibly delisted; no price data found  (1d 2025-07-29 -> 2025-08-29)

ANSS is skipped
ANTM

$ANTM: possibly delisted; no timezone found

ANTM is skipped
AON
AOS
APA
APD
APH
APTV
ARE
ATO
ATVI

$ATVI: possibly delisted; no timezone found

ATVI is skipped
AVB
AVGO
AVY
AWK
AXP
AZO
BA
BAC
BAX
BBY
BDX
BEN
BF.B

$BF.B: possibly delisted; no price data found  (1d 2024-08-29 -> 2025-08-29)

BF.B is skipped
BIIB
BIO
BK
BKNG
BKR
BLK
BLL

$BLL: possibly delisted; no timezone found

BLL is skipped
BMY
BR
BRK.B

$BRK.B: possibly delisted; no timezone found

BRK.B is skipped
BSX
BWA
BXP
C
CAG
CAH
CARR
CAT
CB
CBOE
CBRE
CCI
CCL
CDNS
CDW
CE
CERN

$CERN: possibly delisted; no timezone found

CERN is skipped
CF
CFG
CHD
CHRW
CHTR
CI
CINF
CL
CLX
CMA
CMCSA
CME
CMG
CMI
CMS
CNC
CNP
COF
COG

$COG: possibly delisted; no timezone found

COG is skipped
COO
COP
COST
COTY
CPB
CPRT
CRM
CSCO
CSX
CTAS
CTL

$CTL: possibly delisted; no timezone found

CTL is skipped
CTSH
CTVA
CTXS

$CTXS: possibly delisted; no timezone found

CTXS is skipped
CVS
CVX
CXO

$CXO: possibly delisted; no timezone found

CXO is skipped
D
DAL
DD
DE
DFS

$DFS: possibly delisted; no timezone found

DFS is skipped
DG
DGX
DHI
DHR
DIS
DISCA

$DISCA: possibly delisted; no timezone found

DISCA is skipped
DISCK

$DISCK: possibly delisted; no timezone found

DISCK is skipped
DISH

$DISH: possibly delisted; no timezone found

DISH is skipped
DLR
DLTR
DOV
DOW
DPZ
DRE

$DRE: possibly delisted; no timezone found

DRE is skipped
DRI
DTE
DUK
DVA
DVN
DXC
DXCM
EA
EBAY
ECL
ED
EFX
EIX
EL
EMN
EMR
EOG
EQIX
EQR
ES
ESS
ETFC

$ETFC: possibly delisted; no timezone found

ETFC is skipped
ETN
ETR
EVRG
EW
EXC
EXPD
EXPE
EXR
F
FANG
FAST
FB
FB is skipped
FBHS

$FBHS: possibly delisted; no timezone found

FBHS is skipped
FCX
FDX
FE
FFIV
FIS
FISV

$FISV: possibly delisted; no timezone found

FISV is skipped
FITB
FLIR

$FLIR: possibly delisted; no timezone found

FLIR is skipped
FLS
FLT

$FLT: possibly delisted; no timezone found

FLT is skipped
FMC
FOX
FOXA
FRC

$FRC: possibly delisted; no timezone found

FRC is skipped
FRT
FTI
FTNT
FTV
GD
GE
GILD
GIS
GL
GLW
GM
GOOG
GOOGL
GPC
GPN
GPS

$GPS: possibly delisted; no timezone found

GPS is skipped
GRMN
GS
GWW
HAL
HAS
HBAN
HBI
HCA
HD
HES

$HES: possibly delisted; no price data found  (1d 2025-07-29 -> 2025-08-29)

HES is skipped
HFC

$HFC: possibly delisted; no timezone found

HFC is skipped
HIG
HII
HLT
HOLX
HON
HPE
HPQ
HRB
HRL
HSIC
HST
HSY
HUM
HWM
IBM
ICE
IDXX
IEX
IFF
ILMN
INCY
INFO
INFO is skipped
INTC
INTU
IP
IPG
IPGP
IQV
IR
IRM
ISRG
IT
ITW
IVZ
J
JBHT
JCI
JKHY
JNJ
JNPR

$JNPR: possibly delisted; no price data found  (1d 2025-07-29 -> 2025-08-29)

JNPR is skipped
JPM
K
KEY
KEYS
KHC
KIM
KLAC
KMB
KMI
KMX
KO
KR
KSS
KSU

$KSU: possibly delisted; no timezone found

KSU is skipped
L
LB
LDOS
LEG
LEN
LH
LHX
LIN
LKQ
LLY
LMT
LNC
LNT
LOW
LRCX
LUV
LVS
LW
LYB
LYV
MA
MAA
MAR
MAS
MCD
MCHP
MCK
MCO
MDLZ
MDT
MET
MGM
MHK
MKC
MKTX
MLM
MMC
MMM
MNST
MO
MOS
MPC
MRK
MRO

$MRO: possibly delisted; no timezone found

MRO is skipped
MS
MSCI
MSFT
MSI
MTB
MTD
MU
MXIM

$MXIM: possibly delisted; no timezone found

MXIM is skipped
MYL

$MYL: possibly delisted; no timezone found

MYL is skipped
NBL

$NBL: possibly delisted; no timezone found

NBL is skipped
NCLH
NDAQ
NEE
NEM
NFLX
NI
NKE
NLOK

$NLOK: possibly delisted; no timezone found

NLOK is skipped
NLSN

$NLSN: possibly delisted; no timezone found

NLSN is skipped
NOC
NOV
NOW
NRG
NSC
NTAP
NTRS
NUE
NVDA
NVR
NWL
NWS
NWSA
O
ODFL
OKE
OMC
ORCL
ORLY
OTIS
OXY
PAYC
PAYX
PBCT

$PBCT: possibly delisted; no timezone found

PBCT is skipped
PCAR
PEAK

$PEAK: possibly delisted; no timezone found

PEAK is skipped
PEG
PEP
PFE
PFG
PG
PGR
PH
PHM
PKG
PKI

$PKI: possibly delisted; no timezone found

PKI is skipped
PLD
PM
PNC
PNR
PNW
PPG
PPL
PRGO
PRU
PSA
PSX
PVH
PWR
PXD

$PXD: possibly delisted; no timezone found

PXD is skipped
PYPL
QCOM
QRVO
RCL
RE

$RE: possibly delisted; no timezone found

RE is skipped
REG
REGN
RF
RHI
RJF
RL
RMD
ROK
ROL
ROP
ROST
RSG
RTX
SBAC
SBUX
SCHW
SEE
SHW
SIVB

$SIVB: possibly delisted; no timezone found

SIVB is skipped
SJM
SLB
SLG
SNA
SNPS
SO
SPG
SPGI
SRE
STE
STT
STX
STZ
SWK
SWKS
SYF
SYK
SYY
T
TAP
TDG
TDY
TEL
TFC
TFX
TGT
TIF

$TIF: possibly delisted; no timezone found

TIF is skipped
TJX
TMO
TMUS
TPR
TROW
TRV
TSCO
TSN
TT
TTWO
TWTR

$TWTR: possibly delisted; no timezone found

TWTR is skipped
TXN
TXT
TYL
UA
UAA
UAL
UDR
UHS
ULTA
UNH
UNM
UNP
UPS
URI
USB
V
VAR

$VAR: possibly delisted; no timezone found

VAR is skipped
VFC
VIAC

$VIAC: possibly delisted; no timezone found

VIAC is skipped
VLO
VMC
VNO
VRSK
VRSN
VRTX
VTR
VZ
WAB
WAT
WBA
WDC
WEC
WELL
WFC
WHR
WLTW

$WLTW: possibly delisted; no timezone found

WLTW is skipped
WM
WMB
WMT
WRB
WRK

$WRK: possibly delisted; no timezone found

WRK is skipped
WST
WU
WY
WYNN
XEL
XLNX

$XLNX: possibly delisted; no timezone found

XLNX is skipped
XOM
XRAY
XRX
XYL
YUM
ZBH
ZBRA
ZION
ZTS

In [30]:
hqm_df.columns = hqm_columns = [
    'Ticker',
    'Price',
    'Number of Shares to Buy',
    'One-year Price Return',
    'One-year Return Percentile',
    'Six-month Price Return',
    'Six-month Return Percentile',
    'Three-month Price Return',
    'Three-month Return Percentile',
    'One-month Price Return',
    'One-month Return Percentile',
    
]

In [31]:
hqm_df

,Ticker,Price,Number of Shares to Buy,One-year Price Return,One-year Return Percentile,Six-month Price Return,Six-month Return Percentile,Three-month Price Return,Three-month Return Percentile,One-month Price Return,One-month Return Percentile
0,A,124.96,N/A,0.886333,N/A,0.978855,N/A,1.070741,N/A,1.043507,N/A
1,AAL,13.25,N/A,1.293945,N/A,0.909403,N/A,1.138316,N/A,1.141258,N/A
2,AAP,60.52,N/A,1.32628,N/A,1.65543,N/A,1.149734,N/A,1.052339,N/A
3,AAPL,232.56,N/A,1.015395,N/A,0.983875,N/A,1.143648,N/A,1.087048,N/A
4,ABBV,207.92,N/A,1.098755,N/A,1.031854,N/A,1.143115,N/A,1.099233,N/A
...,...,...,...,...,...,...,...,...,...,...,...
500,YUM,145.47,N/A,1.08671,N/A,0.948197,N/A,1.015852,N/A,1.006643,N/A
501,ZBH,105.06,N/A,0.922649,N/A,1.007138,N/A,1.140332,N/A,1.098609,N/A
502,ZBRA,322.0,N/A,0.932145,N/A,1.038542,N/A,1.100667,N/A,0.954753,N/A
503,ZION,57.815,N/A,1.203456,N/A,1.092248,N/A,1.233231,N/A,1.048124,N/A
504,ZTS,154.79,N/A,0.851901,N/A,0.939367,N/A,0.936039,N/A,1.031796,N/A

In [13]:
! pwd

/Users/lin/github/quant

In [32]:
hqm_df.to_csv('hqm_df.csv', index=False)

## Calculating Momentum Percentiles

We now need to calculate momentum percentile scores for every stock in the universe. More specifically, we need to calculate percentile scores for the following metrics for every stock:

* `One-Year Price Return`
* `Six-Month Price Return`
* `Three-Month Price Return`
* `One-Month Price Return`

Here's how we'll do this:

In [34]:
hqm_df = pd.read_csv('/Users/lin/github/quant/hqm_df.csv')

In [35]:
time_periods = ['One-year', 'Six-month', 'Three-month', 'One-month']

for row in hqm_df.index:
    for time_period in time_periods:
        return_col = f'{time_period} Price Return'
        percentile_col = f"{time_period} Return Percentile"
        hqm_df.loc[row, percentile_col] = stats.percentileofscore(hqm_df[return_col], hqm_df.loc[row, return_col])

In [36]:
hqm_df.sort_values('One-year Return Percentile', ascending=False).head(10)

,Ticker,Price,Number of Shares to Buy,One-year Price Return,One-year Return Percentile,Six-month Price Return,Six-month Return Percentile,Three-month Price Return,Three-month Return Percentile,One-month Price Return,One-month Return Percentile
441,TPR,102.61,NaN,2.580443,100.000000,1.231982,83.366337,1.274615,91.485149,0.947461,16.633663
454,UAL,105.08,NaN,2.524141,99.801980,1.133182,73.267327,1.329453,94.851485,1.132206,92.673267
391,RE,365.84,NaN,2.192333,99.504950,1.543616,98.316832,1.459894,98.514851,1.124451,92.178218
390,RCL,365.84,NaN,2.192333,99.504950,1.543616,98.316832,1.459894,98.514851,1.124451,92.178218
50,AVGO,308.65,NaN,1.969635,99.207921,1.585169,98.613861,1.258088,90.297030,1.037479,63.960396
84,CCL,32.49,NaN,1.935080,99.009901,1.379618,93.663366,1.409545,97.227723,1.100610,89.702970
340,NRG,148.66,NaN,1.875064,98.811881,1.432362,95.247525,0.942772,16.039604,0.934145,12.277228
233,HWM,176.16,NaN,1.824168,98.613861,1.322352,89.900990,1.036250,40.396040,0.923833,9.900990
422,STX,172.38,NaN,1.788782,98.415842,1.742788,99.801980,1.474102,99.009901,1.135947,93.069307
332,NFLX,1231.45,NaN,1.784710,98.217822,1.270112,86.534653,1.019412,34.257426,1.044487,68.712871

## Calculating the HQM Score

We'll now calculate our `HQM Score`, which is the high-quality momentum score that we'll use to filter for stocks in this investing strategy.

The `HQM Score` will be the arithmetic mean of the 4 momentum percentile scores that we calculated in the last section.

To calculate arithmetic mean, we will use the `mean` function from Python's built-in `statistics` module.

In [37]:
for row in hqm_df.index:
    momentum_percentiles = []
    for time_period in time_periods:
        momentum_percentiles.append(hqm_df.loc[row, f'{time_period} Return Percentile'])
    hqm_df.loc[row, 'HQM Score'] = mean(momentum_percentiles)

## Selecting the 50 Best Momentum Stocks

As before, we can identify the 50 best momentum stocks in our universe by sorting the DataFrame on the `HQM Score` column and dropping all but the top 50 entries.

In [39]:
top_50 = hqm_df.sort_values('HQM Score', ascending=False).head(50)

In [44]:
top_50.reset_index(inplace=True)

In [45]:
top_50

,index,Ticker,Price,Number of Shares to Buy,One-year Price Return,One-year Return Percentile,Six-month Price Return,Six-month Return Percentile,Three-month Price Return,Three-month Return Percentile,One-month Price Return,One-month Return Percentile,HQM Score
0,479,WDC,82.04,NaN,1.718684,97.425743,1.700659,99.405941,1.544398,99.603960,1.181282,97.623762,98.514851
1,422,STX,172.38,NaN,1.788782,98.415842,1.742788,99.801980,1.474102,99.009901,1.135947,93.069307,97.574257
2,391,RE,365.84,NaN,2.192333,99.504950,1.543616,98.316832,1.459894,98.514851,1.124451,92.178218,97.128713
3,390,RCL,365.84,NaN,2.192333,99.504950,1.543616,98.316832,1.459894,98.514851,1.124451,92.178218,97.128713
4,37,ANET,136.23,NaN,1.599789,95.643564,1.497527,97.227723,1.501985,99.207921,1.154491,95.445545,96.881188
5,202,GLW,68.93,NaN,1.662501,96.633663,1.422502,94.851485,1.383879,96.831683,1.170885,96.633663,96.237624
6,493,WYNN,126.74,NaN,1.700545,97.029703,1.449532,95.643564,1.376126,96.237624,1.139284,93.663366,95.643564
7,152,EBAY,92.80,NaN,1.627992,96.435644,1.476012,96.435644,1.281412,91.881188,1.173941,96.831683,95.396040
8,331,NEM,72.97,NaN,1.421566,89.306931,1.772761,100.000000,1.378874,96.435644,1.143193,94.059406,94.950495
9,84,CCL,32.49,NaN,1.935080,99.009901,1.379618,93.663366,1.409545,97.227723,1.100610,89.702970,94.900990
10,290,LVS,57.71,NaN,1.504301,92.871287,1.338705,90.693069,1.414654,97.425743,1.104508,90.099010,92.772277
11,73,BWA,42.91,NaN,1.277678,76.039604,1.459892,95.841584,1.286704,92.079208,1.192939,97.821782,90.445545
12,236,IDXX,647.03,NaN,1.332818,83.960396,1.463836,96.039604,1.248924,88.118812,1.137335,93.267327,90.346535
13,454,UAL,105.08,NaN,2.524141,99.801980,1.133182,73.267327,1.329453,94.851485,1.132206,92.673267,90.148515
14,92,CHRW,129.29,NaN,1.271448,75.445545,1.318457,89.702970,1.357550,95.841584,1.283403,99.603960,90.148515
15,285,LNC,42.77,NaN,1.401925,88.316832,1.153163,77.425743,1.306105,94.059406,1.208875,99.009901,89.702970
16,462,URI,955.24,NaN,1.314896,81.584158,1.509815,97.425743,1.330759,95.049505,1.059921,79.009901,88.267327
17,176,FAST,50.18,NaN,1.541408,94.257426,1.367040,93.267327,1.208751,83.168317,1.073828,81.980198,88.168317
18,50,AVGO,308.65,NaN,1.969635,99.207921,1.585169,98.613861,1.258088,90.297030,1.037479,63.960396,88.019802
19,44,APH,111.94,NaN,1.696755,96.831683,1.726749,99.603960,1.259979,90.495050,1.038212,64.356436,87.821782
20,172,EXPE,214.71,NaN,1.532499,94.059406,1.115264,68.712871,1.269118,91.287129,1.148201,94.653465,87.178218
21,293,LYV,166.62,NaN,1.708923,97.227723,1.180028,80.198020,1.225868,85.346535,1.088450,85.148515,86.980198
22,426,SYF,76.58,NaN,1.562637,94.851485,1.298547,88.118812,1.300308,93.465347,1.045158,69.504950,86.485149
23,225,HPE,23.16,NaN,1.257088,72.079208,1.199888,81.980198,1.307704,94.455446,1.106017,90.891089,84.851485
24,324,MU,122.00,NaN,1.269372,74.752475,1.343669,91.188119,1.238613,87.029703,1.088800,85.841584,84.702970
25,325,MXIM,122.00,NaN,1.269372,74.752475,1.343669,91.188119,1.238613,87.029703,1.088800,85.841584,84.702970
26,326,MYL,122.00,NaN,1.269372,74.752475,1.343669,91.188119,1.238613,87.029703,1.088800,85.841584,84.702970
27,327,NBL,122.00,NaN,1.269372,74.752475,1.343669,91.188119,1.238613,87.029703,1.088800,85.841584,84.702970
28,240,INCY,83.70,NaN,1.272036,75.643564,1.137847,73.861386,1.289279,92.673267,1.162500,96.435644,84.653465
29,205,GOOGL,211.64,NaN,1.294292,77.623762,1.257649,85.940594,1.217794,84.752475,1.099829,89.504950,84.455446
30,82,CBRE,161.99,NaN,1.402997,88.712871,1.147482,75.247525,1.301961,93.663366,1.060630,79.603960,84.306931
31,204,GOOG,212.37,NaN,1.285015,76.633663,1.249956,85.742574,1.215001,84.158416,1.098655,88.514851,83.762376
32,276,LDOS,181.36,NaN,1.171715,63.168317,1.427093,95.049505,1.214017,83.960396,1.119575,91.683168,83.465347
33,328,NCLH,25.39,NaN,1.395055,87.920792,1.078590,60.396040,1.438527,97.821782,1.094396,87.524752,83.415842
34,122,CVS,72.14,NaN,1.315544,81.782178,1.146213,75.049505,1.176428,77.623762,1.206355,98.811881,83.316832
35,246,IPGP,84.98,NaN,1.213133,68.514851,1.469226,96.237624,1.256357,90.099010,1.057097,77.623762,83.118812
36,313,MO,66.42,NaN,1.341294,84.554455,1.238334,84.752475,1.141618,69.900990,1.134997,92.871287,83.019802
37,64,BK,106.10,NaN,1.614379,96.237624,1.230806,83.168317,1.193794,80.594059,1.046661,70.693069,82.673267
38,457,ULTA,530.63,NaN,1.439856,90.495050,1.444166,95.445545,1.250424,88.514851,1.021169,54.653465,82.277228
39,2,AAP,60.52,NaN,1.326280,82.772277,1.655430,99.009901,1.149734,72.475248,1.052339,74.455446,82.178218
40,210,GS,751.22,NaN,1.515766,93.267327,1.242147,85.544554,1.240657,87.722772,1.033528,61.980198,82.128713
41,106,COF,227.14,NaN,1.582087,95.148515,1.150479,76.732673,1.178384,78.118812,1.059340,78.514851,82.128713
42,107,COG,227.14,NaN,1.582087,95.148515,1.150479,76.732673,1.178384,78.118812,1.059340,78.514851,82.128713
43,11,ADM,62.66,NaN,1.066608,46.336634,1.359597,92.871287,1.306274,94.257426,1.149673,94.851485,82.079208
44,345,NVDA,180.17,NaN,1.485060,92.277228,1.526852,97.821782,1.266661,91.089109,1.012418,46.732673,81.980198
45,253,IVZ,22.06,NaN,1.354212,85.346535,1.310527,89.504950,1.515469,99.405941,1.020027,53.465347,81.930693
46,213,HAS,81.60,NaN,1.255748,71.881188,1.275222,86.930693,1.227738,85.544554,1.076780,82.574257,81.732673
47,102,CMI,401.92,NaN,1.327586,83.168317,1.117439,69.504950,1.241493,87.920792,1.089748,86.336634,81.732673
48,318,MS,150.18,NaN,1.502762,92.475248,1.173493,79.207921,1.180510,78.811881,1.053821,75.841584,81.584158
49,288,LRCX,104.09,NaN,1.286714,76.831683,1.363699,93.069307,1.215481,84.356436,1.047288,71.287129,81.386139

## Calculating the Number of Shares to Buy

We'll use the `portfolio_input` function that we created earlier to accept our portfolio size. Then we will use similar logic in a `for` loop to calculate the number of shares to buy for each stock in our investment universe.

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

## Creating the Formats We'll Need For Our .xlsx File

You'll recall from our first project that formats include colors, fonts, and also symbols like % and $. We'll need four main formats for our Excel document:

* String format for tickers
* \$XX.XX format for stock prices
* \$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase

Since we already built our formats in the last section of this course, I've included them below for you. Run this code cell before proceeding.

In [ ]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_template = writer.book.add_format(
        {
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

dollar_template = writer.book.add_format(
        {
            'num_format':'$0.00',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

integer_template = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

percent_template = writer.book.add_format(
        {
            'num_format':'0.0%',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

## Saving Our Excel Output

As before, saving our Excel output is very easy: